name: publish to easyabp.io
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         persist-credentials: false

      - name: Find and Replace
        uses: shitiomatic/str-replace@master
        with:
          find: \]\((/docs/)
          replace: "](/modules/${{ github.event.repository.name }}/"
          include: docs/

      - name: Read README.md
        id: read
        uses: juliangruber/read-file-action@v1
        with:
          path: docs/README.md

      - name: Echo README.md
        run: echo ${{ steps.read.outputs.content }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.EASYABP_IO_ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: docs
          REPOSITORY_NAME: EasyAbp/easyabp.github.io
          TARGET_FOLDER: docs/modules/${{ github.event.repository.name }}