name: publish to easyabp.io
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        uses: shitiomatic/str-replace@master
        with:
          find: \]\((/docs/)
          replace: "](/modules/${{ github.event.repository.name }}/"
          include: docs/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          ACCESS_TOKEN: ${{ secrets.EASYABP_IO_ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: docs
          REPOSITORY_NAME: EasyAbp/easyabp.github.io
          TARGET_FOLDER: modules/${{ github.event.repository.name }}
          SILENT: false