name: publish to easyabp.io
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Find and Replace
        uses: shitiomatic/str-replace@master
        with:
          find: \]\((/docs/)
          replace: "](/modules/${{ github.event.repository.name }}/"
          include: docs/

      - name: Pull repo and change files
        id: change
        run: |
          ls
          git clone https://github.com/EasyAbp/easyabp.github.io
          cd easyabp.github.io
          rm -rf docs/modules/${{ github.event.repository.name }}
          rm -rf docs/.vuepress/public/modules/${{ github.event.repository.name }}
          cp -rf ../docs/ docs/modules/${{ github.event.repository.name }}
          cp -rf ../docs/ docs/.vuepress/public/modules/${{ github.event.repository.name }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          echo "##[set-output name=diff;]$(git diff)"

      - name: Commit files
        if: steps.change.outputs.diff
        run: |
          git commit -m "Update the docs of ${{ github.event.repository.name }}" -a

      - name: Push changes
        if: steps.change.outputs.diff
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.EASYABP_IO_ACCESS_TOKEN }}
          repository: EasyAbp/easyabp.github.io
          directory: easyabp.github.io