name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200
          source-url: https://nuget.pkg.github.com/EasyAbp/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: dotnet build
        run: dotnet build -c Release

      - name: dotnet pack
        run: dotnet pack -c Release --no-build -o dest

      - name: dotnet nuget push
        run: dotnet nuget push dest\*.nupkg -s "github" --skip-duplicate